global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'movie-api'
    static_configs:
      - targets: ['back:8000']
    metrics_path: /metrics
    scrape_interval: 3s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']